name: photography-build-workflow

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - run: echo  ${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Angular CLI
        run: npm i -g @angular/cli
      - name: Install packages
        run: npm i
      - name: Build the application
        run: npm run build
        env:
          CI: true
